CREATE DATABASE IF NOT EXISTS chapala;
USE chapala;

CREATE TABLE IF NOT EXISTS cortes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(65) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    imagen LONGBLOB
);